{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\n7allure_测试报告.py:14: AssertionError"}, "description": "this test fails", "start": 1728998716396, "stop": 1728998716396, "uuid": "86095ca3-e663-413d-b850-4882e1fb6ec2", "historyId": "05a9c8a1ebdc17ab47a2170eff3e80fd", "testCaseId": "05a9c8a1ebdc17ab47a2170eff3e80fd", "fullName": "7allure_测试报告#test_failure", "labels": [{"name": "suite", "value": "7allure_测试报告"}, {"name": "host", "value": "DESKTOP-HA7F4SE"}, {"name": "thread", "value": "12972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "7allure_测试报告"}]}